# config postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/ponto_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# debug sql 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=projetosNassau
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=pontoeletronico

admin.codigo=ADMIN123